# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sanitycheck2react' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  
  pod 'PDFNet', podspec: 'https://www.pdftron.com/downloads/ios/cocoapods/pdfnet/latest.podspec'

end

target 'sanitycheck2react-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sanitycheck2react-tvOS

  target 'sanitycheck2react-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
